### ISSUE TITLE
[Research] Books APIs analysis

### ISSUE THREAD

**Issue by MadameSheema** [franksparks/BookJourney#2]
## Summary
Research on various books API for our project. The goal is to identify the best solution that meets our requirements.

## APIs to analyze
1. [Open Library API](https://openlibrary.org/developers/api) - https://www.youtube.com/watch?v=reN_okp2Gq4
2. [Google Books API](https://developers.google.com/books?hl=es-419)
3. [Amazon Books API](https://webservices.amazon.com/paapi5/documentation/)
4. Others?

## Requirements
* Easy to integrate with next.js and support for REST
* Access to detailed information about books. I.E: Authors, genres...
* Search capabilities to allow users to find a book by title, author, ISBN or other criteria
* Comprehensive documentation
* Ensure that the API's licensing terms are compatible with our project's needs
* Sufficient API quotas to handle our project
* Ability to get new releases
*  Consideration of any costs associated with using the API, including free tiers

## Expected output
Per each one of the investigated frameworks:

1. The list of the above requirements that are supported
1. Any other non-listed requirement that might be beneficial for our project
2. Pros and cons
3. Any additional consideration discovered during the research.

## Open Library API doc
Lorem Ipsum

More info:
- https://publicapis.io/open-library-api-api/

## Google Books API doc
Lorem Ipsum

## Amazon Books API doc
Lorem Ipsum

**Comment by franksparks** [comment]
### Google Books API doc

- [x] Easy to integrate with next.js and support for REST
- [x] Access to detailed information about books. I.E: Authors, genres...
- [x] Search capabilities to allow users to find a book by title, author, ISBN or other criteria
- [x] Comprehensive documentation
- [x] Ensure that the API's licensing terms are compatible with our project's needs
- [x] Sufficient API quotas to handle our project
- [x] Ability to get new releases
- [x] Consideration of any costs associated with using the API, including free tiers

---

- Book information provided includes (but not limited to):
  - title, author/s, publishedDate, isbn10, isbn13, pagecount, printType, category(genre), language, cover, etc.

Links:
- [Google Books API Documentation](https://developers.google.com/books/docs/v1/getting_started?csw=1&hl=es-419)
- [GET request explorer](https://developers.google.com/books/docs/v1/reference/volumes/list?hl=es-419&apix_params=%7B"q"%3A"isbn%3A8433973290"%7D)
