### ISSUE TITLE
Data Model - initial discussion

### ISSUE THREAD

**Issue by franksparks** [franksparks/BookJourney#4]
Decide the initial structure of entities to be implemented in order to start coding.

Initial DataModel can be found [here](https://drive.google.com/file/d/1Dt3hN7KhW-8pzVtvf2_ku9rO3ihSNjas/view?usp=drive_link)

![Image](https://github.com/franksparks/BookJourney/assets/35843964/7201ce50-a3cf-4e50-8db3-3a1b0b437c1e)

**Comment by franksparks** [comment]
Implemented [v0.1 datamodel](https://app.diagrams.net/#G1Dt3hN7KhW-8pzVtvf2_ku9rO3ihSNjas#%7B"pageId"%3A"yntjt9WMivu8fIEi1uBh"%7D). 

For now, _mongodb_ has been configured as provider.

**Comment by vedderzeznick** [comment]
I added the new model for Author (really simple), also completed some additional fields in the Book model, and created the relations many to many where needed
